#!/bin/bash

########################  MAIN

_echot "------- install"
packages="bless ghex wxhexeditor"
packages+=" lnav mkisofs net-tools pv xsysinfo"
# sysstat
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- bless"
path=${HOME}/.config/bless/layouts/
[ -d "${path}" ] || mkdir -p ${path}
cp ${_PATH_BASE}/conf/bless/* ${path}/
