#!/bin/bash
#
# write by Aguy

_echoT "\n==========================================  ${_PART}"

########################  MAIN

_echot "------------------  install"
packages=" mariadb-client postgresql-client"
# sysstat
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

########################  END

_echoT "===================== ${_PART} end"
_partadd "${_PART}" "${_FILE_DONE}"
