#!/bin/bash

_echot "------- tools"
packages="dnsutils net-tools netcat-traditional traceroute whois xinetd"
packages+=" bmon darkstat dstat hping3 iftop ifstat tcpdump vnstat"
# ibmonitor
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }
