#!/bin/bash

########################  MAIN

_echot "------- install"
packages="cython3 python3-pip pipx"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

packages="virtualenv grip"
for package in ${packages}; do
	_echot "------- pipx"
	_eval pipx install ${package}
done
