#!/bin/bash
#
# write by Aguy

_echot "------------------ apt repository"
sudo add-apt-repository -y ppa:wireshark-dev/stable
sudo apt update

_echot "------------------ install"
packages="tshark wireshark"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------------------ wireshark"
cp ${_PATH_BASE}/xtra/org.wireshark.Wireshark.desktop ~/.local/share/applications/

########################  END

_partadd "${_PART}" "${_FILE_DONE}"
