#!/bin/bash

_echot "------- apt repository"
sudo add-apt-repository -yn ppa:wireshark-dev/stable
${_CMD} update

_echot "------- install"
packages="tshark wireshark"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }
