#!/bin/bash
#
# write by Aguy

_echot "------- tlp"
packages="tlp tlp-rdw"
# acpi
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- tlp"
_service enable tlp

_echot "------- enable acpid"
service=acpid
_service enable ${service}
_service start ${service}

#str=" acpi_backlight=vendor" # just try
#str+=" fbcon=nodefer" # just try
#if [ "${str}" ] && ! grep -q '^GRUB_CMDLINE_LINUX=.*${str}' ${file}; then
#	 sudo sed -i "/^GRUB_CMDLINE_LINUX=/ s|\"$|${str}\"|" ${file}
#fi

