#!/bin/bash
#
# write by Aguy

_echot "------- install"
packages="nextcloud-desktop nextcloud-desktop-cmd nautilus-nextcloud"
# csync-owncloud
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }
