#!/bin/bash
#
# write by Aguy

_echot "------------------ install"
packages="virtualbox"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------------------ virtualbox"
sudo adduser ${USER} vboxusers

########################  END

_partadd "${_PART}" "${_FILE_DONE}"
