#!/bin/bash

########################  REQUIRED

file_meld_conf=${_PATH_BASE}/conf/soft/meld-dark.xml
file_tmux_desktop=${_PATH_BASE}/xtra/org.gnome.Terminal-tmux.desktop
file_profile=${_PATH_BS}/conf/.profile
_require ${file_meld_conf} ${file_profile} ${file_tmux_desktop}

pth_vim=${_PATH_BASE}/conf/vim
pth_wp=${_PATH_BASE}/xtra/wp
_requirep ${pth_vim} ${pth_wp}

########################  SYSTEM

_echot "------- bash-completion"
_evalr "cp -a ${_PATH_BASE}/xtra/bash-completion/* /usr/share/bash-completion/completions/"

_echot "------- vim links edit"
for file in /usr/bin/edit /usr/bin/editor; do
	[ -e ${file} ] && _evalr rm ${file}
	_evalr ln -sv /usr/bin/vim ${file}
done

_echot "------- vim colors"
_evalr cp ${pth_vim}/* /usr/share/vim/vim*/colors/

_echot "------- vim conf"
file=/etc/vim/vimrc
sudo sed -i "s|^\"\(syntax\).*|\1 on|" ${file}
opts="background=dark showmatch"
# uncomment
for opt in ${opts}; do
	sudo sed -i "s|^\"\(set ${opt}.*\)$|\1|" ${file}
done

_echot "------- nano"
for str in conf install; do
	_evalr cp -a /usr/share/nano/sh.nanorc /usr/share/nano/${str}.nanorc
	sudo sed -i 's|^\(syntax \).*|\1"'${str}'" "\.'${str}'$"|' /usr/share/nano/${str}.nanorc
done
file=/etc/nanorc
_keepcp ${file}
sudo sed -i 's|^.*\(set tabsize\).*|\1 4|' ${file}
sudo sed -i 's|^\(set cut.*\)$|# \1|' ${file}
sudo sed -i 's|^\(set linenumbers.*\)$|# \1|' ${file}
sudo sed -i '/^# *include/ s/^# //' ${file}
# uncomment options
# various
opts="constantshow historylog matchbrackets multibuffer nohelp softwrap "
# color
opts+="errorcolor functioncolor keycolor numbercolor selectedcolor statuscolor stripecolor titlecolor"
for opt in ${opts}; do
	sudo sed -i "s|^.*\(set $opt .*\)$|\1|"  ${file}
done

_echot "------- meld style"
file=/usr/share/meld/styles/meld-dark.xml
_keepmv ${file}
_evalr cp ${file_meld_conf} ${file}

_echot "------- wp"
pth=/usr/share/backgrounds
_evalr cp ${pth_wp}/* ${pth}/
_evalr chmod 644 ${pth}/*

########################  USER

_echot "------- path"
pth=~/.local/share/applications
! [ -d "$pth" ] && mkdir -p "$pth"

_echot "------- user icons"
pth=${HOME}/.local/share/icons
_eval cp ${_PATH_BASE}/icons/* ${pth}/

_echot "------- user conf"
for file in .nanorc .tmux.conf .vimrc; do
	pth=${HOME}/${file}
	_keepmv "${pth}"
	_eval ln -s "${_PATH_BS}/conf/${file}" "${pth}"
done

_echot "------- gtk styles"
pth_gtk=${HOME}/.local/share/gtksourceview-5/styles
pth=${_PATH_BASE}/conf/styles
if [ -e  "${pth_gtk}" ]; then
	_eval cp -a ${pth}/* ${pth_gtk}/
else
	_eval ln -s ${pth_gtk} ${pth}
fi

_echot "------- gtk languages"
pth_gtk=${HOME}/.local/share/gtksourceview-5/language-specs
pth=${_PATH_BASE}/conf/lang
if [ -e  "${pth_gtk}" ]; then
	_eval cp -a ${pth}/* ${pth_gtk}/
else
	_eval ln -s ${pth_gtk} ${pth}
fi

_echot "------- tmux resurect"
file=${HOME}/.tmux.conf
# plugins
pth=${HOME}/.tmux/plugins/resurect
[ -d "${pth}" ] || mkdir -p ${pth}
git clone https://github.com/tmux-plugins/tmux-resurrect ${pth}
grep -q resurrect.tmux ${file} || echo -e "# resurect plugin\nrun-shell ${pth}/resurrect.tmux" >> ${file}
# set conf file
tmux source-file ${file} 2>/dev/null

_echot "------- tmux restore"
_keepmvts ${HOME}/.tmux
file="${_PATH_BASE}/xtra/user.tmux.tar.gz"
_eval tar xzf ${file} -C ${HOME}/

_echot "------- tmux desktop"
_eval cp ${file_tmux_desktop} ${HOME}/.local/share/applications/
_eval chmod +x ${HOME}/.local/share/applications/${file_tmux_desktop##*/}

_echot "------- aegisub"
pth=${HOME}/.aegisub/
[ -d "${pth}" ] || _eval mkdir -p ${pth}
_eval cp ${_PATH_BASE}/conf/aegisub-config.json ${pth}

_echot "------- gedit settings"
#dconf write /org/nemo/extensions/nemo-terminal/default-visible false
#gsettings set org.gnome.gedit.preferences.ui max-recents 30
gsettings set org.gnome.gedit.preferences.ui side-panel-visible true
gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
gsettings set org.gnome.gedit.preferences.editor tabs-size 4
dconf write /org/gnome/gedit/plugins/sourcecodebrowser/show-line-numbers true
dconf write /org/gnome/gedit/plugins/filebrowser/enable-remote true

_echot "------- gedit plugins path"
pth_plug=${HOME}/.local/share/gedit/plugins
[ -d "${pth_plug}" ] || mkdir -p "${pth_plug}"

_echot "------- gedit / restore-tabs"
pth=restore-tabs
cd ${pth_plug}
_keepmvts ${pth}
curl -o master.zip https://codeload.github.com/raelgc/gedit-restore-tabs/zip/master
unzip master.zip
rm master.zip
mv gedit-restore-tabs-master ${pth}
rm ${pth}/.gitignore
sudo cp ${pth}/org.gnome.gedit.plugins.restoretabs.gschema.xml /usr/share/glib-2.0/schemas/
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/

_echot "------- gedit / duplicate-line"
pth=duplicate-line
cd ${pth_plug}
_keepmvts ${pth}
curl -o master.zip https://codeload.github.com/hardpixel/gedit-duplicate-line/zip/master
unzip master.zip
rm master.zip
mv gedit-duplicate-line-master ${pth}
sed -i 's|^\(\s*modifiers = event.state.*\)|#\1|' ${pth}/duplicate_line.py
sed -i 's|^\(\s*\)\(if modifiers ==.*\)|#\1\2\n\1if event.state \& Gdk.ModifierType.CONTROL_MASK and event.state \& Gdk.ModifierType.SHIFT_MASK:|' ${pth}/duplicate_line.py
#if event.state & Gdk.ModifierType.CONTROL_MASK and event.state & Gdk.ModifierType.SHIFT_MASK:

_echot "------- gedit / gedit-markdown"
pth=markdown_preview
cd ${pth_plug}
_keepmvts ${pth}
curl -o master.zip https://codeload.github.com/maoschanz/gedit-plugin-markdown_preview/zip/master
unzip master.zip
rm master.zip
mv gedit-plugin-markdown_preview-master ${pth}

_echot "------- languages"
_echoA "Close language window after validation."
_askno "Validate to continue"
_eval gnome-language-selector

_echot "------- QT6"
_echoA "After validation, adjust settings for qt6 and close qt6ct window"
_askno "Validate to continue"
qt6ct 2>/dev/null
