#!/bin/bash

########################  REQUIRED

file_meld_conf=${_PATH_BASE}/conf/soft/meld-perso-dark.style-scheme.xml
file_aegisub_conf=${_PATH_BASE}/conf/soft/aegisub-config.json
file_tmux_desktop=${_PATH_BASE}/xtra/org.gnome.Terminal-tmux.desktop
_require ${file_meld_conf} ${file_aegisub_conf} ${file_tmux_desktop}

pth_gtk=${_PATH_BASE}/conf/gtk
pth_vim=${_PATH_BASE}/conf/vim
pth_wp=${_PATH_BASE}/xtra/wp
_requirep ${pth_gtk} ${pth_vim} ${pth_wp}

########################  SYSTEM

_echot "------- profile desktop.sh"
export PATH="${PATH}:${_PATH_BS}"
export QT_QPA_PLATFORMTHEME=qt6ct
file=/etc/profile.d/desktop.sh
sudo sh -c "echo '# PATH
export PATH=\${PATH}:${_PATH_BS}
# QT6
export QT_QPA_PLATFORMTHEME=qt6ct' > ${file}"

_echot "------- vim links edit"
for file in /usr/bin/edit /usr/bin/editor; do
	[ -e ${file} ] && _evalr rm ${file}
	_evalr ln -sv /usr/bin/vim ${file}
done

_echot "------- vim colors"
_evalr cp ${pth_vim}/* /usr/share/vim/vim*/colors/

_echot "------- vim conf"
file=/etc/vim/vimrc
sudo sed -i "s|^\"\(syntax\).*|\1 on|" ${file}
opts="background=dark showmatch"
# uncomment
for opt in ${opts}; do
	sudo sed -i "s|^\"\(set ${opt}.*\)$|\1|" ${file}
done

_echot "------- nano"
for str in conf install; do
	_evalr cp -a /usr/share/nano/sh.nanorc /usr/share/nano/${str}.nanorc
	sudo sed -i 's|^\(syntax \).*|\1"'${str}'" "\.'${str}'$"|' /usr/share/nano/${str}.nanorc
done
file=/etc/nanorc
_keepcp ${file}
sudo sed -i 's|^.*\(set tabsize\).*|\1 4|' ${file}
sudo sed -i 's|^\(set cut.*\)$|# \1|' ${file}
sudo sed -i 's|^\(set linenumbers.*\)$|# \1|' ${file}
sudo sed -i '/^# *include/ s/^# //' ${file}
# uncomment options
opts="constantshow historylog matchbrackets multibuffer nohelp softwrap "
opts+="errorcolor functioncolor keycolor numbercolor selectedcolor statuscolor stripecolor titlecolor"
for opt in ${opts}; do
	sudo sed -i "s|^.*\(set $opt .*\)$|\1|"  ${file}
done

_echot "------- meld style"
pth=/usr/share/meld/styles
_keepmvts ${file}
_evalr cp ${file_meld_conf} ${pth}

_echot "------- wp"
pth=/usr/share/backgrounds
_evalr cp ${pth_wp}/* ${pth}/
_evalr chmod 644 ${pth}/*

########################  USER

_echot "------- user icons"
pth=${HOME}/.local/share/icons
_eval cp ${_PATH_BASE}/icons/* ${pth}/

_echot "------- tmux resurrect"
pth=${HOME}/.tmux/plugins/tmux-resurrect
_eval git clone https://github.com/tmux-plugins/tmux-resurrect ${pth}
grep -sq resurrect.tmux ${file} || echo "# resurrect plugin
run-shell ${pth}/resurrect.tmux" >> ${HOME}/.tmux.conf

_echot "------- tmux resurrect"
pth=${HOME}/.tmux/plugins/tmux-continuum
_eval git clone https://github.com/tmux-plugins/tmux-continuum ${pth}
grep -sq continuum.tmux ${file} || echo "# resurrect continuum
run-shell ${pth}/continuum.tmux" >> ${HOME}/.tmux.conf

_echot "------- tmux themepack"
${_CMD_INS} fonts-powerline && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install packages: ${packages}"; return 1; }
pth=${HOME}/.tmux/themes/tmux-themepack
_eval git clone https://github.com/jimeh/tmux-themepack.git ${pth}
grep -sq tmux-themepack ${file} || echo "# source themepack
source-file ${pth}/powerline/double/cyan.tmuxtheme" >> ${HOME}/.tmux.conf

_echot "------- configuration files"
for file in .nanorc .tmux.conf .vimrc; do
	pth=${HOME}/${file}
	_keepmvts "${pth}"
	_eval cp -a "${_PATH_BS}/conf/${file}" "${pth}"
	_evalr chmod 644 ${pth}
done

_echot "------- tmux source"
_eval tmux new -d
_eval tmux source-file ${HOME}/.tmux.conf

_echot "------- tmux desktop"
_eval cp -a ${file_tmux_desktop} ${HOME}/.local/share/applications/
_evalr chmod 644 ${HOME}/.local/share/applications/${file_tmux_desktop##*/}

_echot "------- gtk4"
pth_to="${HOME}/.local/share/gtksourceview-4"
[ -d "${pth_to}" ] && _keepmvts "${pth_to}"
_eval cp -a ${pth_gtk} ${pth_to}

_echot "------- gtk3"
cd "${HOME}/.local/share"
[ -e "gtksourceview-4" ] || _eval ln -s gtksourceview-4 gtksourceview-3.0

_echot "------- aegisub"
pth=${HOME}/.aegisub/
[ -d "${pth}" ] || _eval mkdir -p ${pth}
_eval cp -a ${file_aegisub_conf} ${pth}
_evalr chmod 644 ${pth}/${file_aegisub_conf##*/}

_echot "------- gedit settings"
#dconf write /org/nemo/extensions/nemo-terminal/default-visible false
#gsettings set org.gnome.gedit.preferences.ui max-recents 30
gsettings set org.gnome.gedit.preferences.ui side-panel-visible true
gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
gsettings set org.gnome.gedit.preferences.editor tabs-size 4
dconf write /org/gnome/gedit/plugins/sourcecodebrowser/show-line-numbers true
dconf write /org/gnome/gedit/plugins/filebrowser/enable-remote true

_echot "------- gedit plugins path"
pth_plug=${HOME}/.local/share/gedit/plugins
[ -d "${pth_plug}" ] || mkdir -p "${pth_plug}"

pth=gedit-restore-tabs
_echot "------- gedit / ${pth}"
cd ${pth_plug}
_keepmvts ${pth}
git clone https://github.com/raelgc/gedit-restore-tabs ${pth}
sudo cp ${pth}/org.gnome.gedit.plugins.restoretabs.gschema.xml /usr/share/glib-2.0/schemas/
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/

pth=gedit-duplicate-line
_echot "------- gedit / ${pth}"
cd ${pth_plug}
_keepmvts ${pth}
git clone https://github.com/hardpixel/gedit-duplicate-line ${pth}
# use ALT-d instead of CTRL-d
sed -i.bak 's|\(Gdk.ModifierType.\).*:|\1MOD1_MASK:|' ${pth}/duplicate_line.py

pth=duplicate
_echot "------- gedit / ${pth}"
cd ${pth_plug}
_keepmvts ${pth}
git clone https://github.com/hannenz/duplicate ${pth}
# use Shift-Ctrl-d, Shift-Alt-d or Alt-d
sed -i.bak "/\s'key': \[.*\],/ s|\[.*\]|['<Shift><Ctrl>d', '<Shift><Alt>d', '<Alt>d']|" ${pth}/duplicateline.py
tar czf ${pth}.tgz ${pth} && rm -fR ${pth}

pth=gedit-plugin-markdown_preview
_echot "------- gedit / ${pth}"
cd ${pth_plug}
_keepmvts ${pth}
git clone https://github.com/maoschanz/gedit-plugin-markdown_preview ${pth}

_echot "------- languages"
_echoA "Close language window after validation."
_askno "Validate to continue"
_eval gnome-language-selector

_echot "------- QT6"
_echoA "After validation, adjust settings for qt6 and close qt6ct window"
_askno "Validate to continue"
qt6ct 2>/dev/null

