#!/bin/bash

if [ -z ${_BTRFS+x} ]; then
	_askyn "BTRFS are used for system?"
	_BTRFS=${_ANSWER/n/}
	_confset _BTRFS "${_BTRFS}"
fi
[ "${_BTRFS}" ] && part_fs="btrfs" || part_fs="nobtrfs"

if [ -z ${_HALT+x} ]; then
	_askyn "Enable halt between each parts?"
	_HALT=${_ANSWER/n/}
	_confset _HALT "${_HALT}"
fi
