#!/bin/bash

_echot "------- upgrade"
_eval ${_PATH_BASE}/bs/upgrade

########################  END

_partadd "pre_${_PART}" "${S_FILE_INSTALL_DONE}"

########################  RESTART

_echoA "Restart your computer to append configuration"
_askno "Validate to reboot"
sudo reboot
