#!/bin/bash

_echot "------- upgrade"
_eval ${_PATH_BASE}/bs/upgrade

########################  END

_partadd "${_PART}" "${_FILE_DONE}"

########################  RESTART

_echoA "Restart your computer to append configuration"
_askno "Validate to reboot"
sudo reboot
