#!/bin/bash

########################  MAIN

_echot "------- system"
packages="curl duf exfatprogs gdebi gnupg gparted hfsprogs htop kpartx most ncdu pv testdisk tmux tree vim"
packages+=" p7zip-full p7zip-rar zip unzip rar unrar"
# oracle-java7-installer ntfsprogs grsync gtk2-engines-pixbuf libnss-myhostname atop fslint dstat icedtea-8-plugin
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- tools"
packages="dconf-editor font-manager gnome-sushi meld qt6ct"
packages+="  gnome-activity-journal gnome-system-monitor gnome-system-tools gnome-tweaks gnome-shell-extension-manager"
# boot-repair backintime-gnome y-ppa-manager numlockx multisystem
packages+=" nautilus-image-converter nautilus-sendto"
# easytag-nautilus nautilus-script-audio-convert

# nautilus-columns nautilus-image-manipulator filemanager-actions nautilus-emblems
packages+=" gedit-plugins gedit-source-code-browser-plugin stopwatch"
# gedit-developer-plugins
# uget-chrome-wrapper nautilus-dropbox nautilus-filename-repairer nautilus-image-converter nautilus-terminal
# compiz-fusion-plugins-extra compizconfig-settings-manager exfat-utils exfat-fuse freefilesync qshutdown solaar unetbootin
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- libreoffice"
packages="libreoffice"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- graphic"
packages="inkscape gimp"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- audio"
packages="audacity easytag gmusicbrowser soundconverter sound-juicer"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- video"
packages="cheese obs-studio simplescreenrecorder "
packages+=" aegisub gnome-subtitles gnome-video-effects-extra handbrake mkvtoolnix-gui mpv totem totem-plugins"
packages+=" gstreamer1.0-plugins-bad libavcodec-extra  ubuntu-restricted-extras"
# qarte
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }
