#!/bin/bash

########################  PRE OUTSIDE

_echot "------- libdvd"
_echo "Launch this following command in an other terminal:"
_echoA "sudo apt install -y libdvdnav4 libdvd-pkg libdvdread8t64"
_askno "After it, Validate to continue"

_echot "------- libdvd conf"
_echo "Launch this following command in an other terminal:"
_echoA "sudo dpkg-reconfigure libdvd-pkg"
_askno "After it, Validate to continue"

_echot "------- ttf"
_echo "Launch this following command in an other terminal:"
_echoA "sudo apt install -y ttf-mscorefonts-installer"
_askno "After it, Validate to continue"

########################  MAIN

_echot "------- system"
packages="curl wget duf exfatprogs gnupg hfsprogs htop most ncdu pv testdisk tree"
packages+=" git gparted tmux vim"
packages+=" p7zip-full p7zip-rar zip unzip rar unrar"
# kpartx ntfsprogs grsync gtk2-engines-pixbuf libnss-myhostname atop fslint dstat icedtea-8-plugin
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install packages: ${packages}"; return 1; }

_echot "------- tools"
packages="dconf-editor font-manager gnome-sushi meld qt6ct stopwatch"
packages+=" gnome-activity-journal gnome-system-monitor gnome-system-tools gnome-tweaks"
# boot-repair backintime-gnome y-ppa-manager numlockx multisystem baobab
packages+=" nautilus-image-converter nautilus-sendto"
# easytag-nautilus nautilus-script-audio-convert nautilus-columns
# nautilus-image-manipulator filemanager-actions nautilus-emblems
# uget-chrome-wrapper nautilus-dropbox nautilus-filename-repairer nautilus-image-converter nautilus-terminal
# compiz-fusion-plugins-extra compizconfig-settings-manager exfat-utils exfat-fuse freefilesync qshutdown solaar unetbootin
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- office"
packages="libreoffice  libreoffice-gtk4 libreoffice-math libreoffice-numbertext libreoffice-qt6"
packages+=" libreoffice-style-breeze libreoffice-style-sifr libreoffice-sdbc-mysql"
packages+=" scribus"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- graphic"
packages="inkscape"
# inkscape-speleo inkscape-textext inkscape-tutorials inkscape-open-symbols inkscape-survex-export"
packages+=" gimp gimp-lensfun gimp-texturize"
# gimp-plugin-registry

_echot "------- media"
packages+=" aegisub cheese gnome-subtitles handbrake mkvtoolnix-gui mpv totem totem-plugins"
packages+=" obs-studio simplescreenrecorder"
packages+=" audacity easytag gmusicbrowser sayonara soundconverter sound-juicer"
packages+=" gnome-video-effects-extra gstreamer1.0-plugins-bad gstreamer1.0-plugins-good"
packages+=" libavcodec-extra ubuntu-restricted-extras"
# chrome-gnome-shell
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }
