#!/bin/bash

########################  SYSTEM

_echot "------- root user"
_ask "Give the password for root" && echo -e "${_ANSWER}\n${_ANSWER}" | sudo passwd root

_echot "------- update grub"
if [ "${_BTRFS}" ];then
	_evalr grub-install ${_DEVICE_GRUB}
	_evalr update-grub
fi



########################  USER

_echot "------- user paths"
paths="${HOME}/.local/bin ${HOME}/.local/share/icons ${HOME}/.local/share/applications"
for path in ${paths}; do
	[ -d "${path}" ] || mkdir -p ${path}
done

_echot "------- .bash_aliases"
file=${HOME}/.bash_aliases
_keepmv ${file}
_eval ln -s ${_PATH_BS}/conf/.bash_aliases ${file}

_echot "------- .bashrc"
file=${HOME}/.bashrc
_keepcp ${file}
_eval "sed -i 's|^\(HISTSIZE\)=.*$|\1=50000|' ${file}"
_eval "sed -i 's|^\(HISTFILESIZE\)=.*$|\1=50000|' ${file}"
_eval "sed -i '/^#force_color_prompt/ s|^#||' ${file}"

_echot "------- color prompt"
sed -i 's|^#\?\(force_color_prompt\).*$|\1=yes|' ${file}

_echot "------- .bashrc PS1"
color='\\[\\033[01;34m\\]' # '\\[\\033[01;32m\\]'
sed -i 's|^\(\s*PS1=\).*00m.*$|\1"\${debian_chroot:+(\$debian_chroot)}'${color}'\\u@\\h\\[\\033[00m\\] \\W'${color}'\\$\\[\\033[00m\\] "|' ${file}
sed -i "/^\s*PS1=.*01;34m/ s|\"|'|g" ${file}

_echot "------- .bashrc aliases"
grep -q ". \${HOME}/.bash_aliases" ${file} || echo "
# bash_aliases
[ -f \${HOME}/.bash_aliases ] && . \${HOME}/.bash_aliases"  >> ${file}

_echot "------- .bashrc source"
. ${file}

_echot "------- profile"
[ -f "${HOME}/.profile" ] || _evalr cp -a /root/.profile ${HOME}/
. ${HOME}/.profile

_echot "------- conf user"
sudo adduser -q ${USER} users
sudo adduser -q ${USER} www-data
sudo adduser -q ${USER} audio
sudo adduser -q ${USER} video
