#!/bin/bash

########################  DATA

_echot "------- data"

anstmp="20241031" && _askno "Give a version of cinelerra-gg to download ($anstmp)" && ver=${_ANSWER:-$anstmp}

pth_opt="/opt/cinelerra"
link_opt="/opt/cinelerra/CinGG.AppImage"
pth_desk=~/.local/share/applications
file_desk=${pth_desk}/cinelerra.desktop
file_bin=/usr/bin/cinelerra

file_desk_conf=${_PATH_BASE}/conf/cinelerra/cinelerra.desktop
file_icon_conf=${_PATH_BASE}/conf/cinelerra/cinelerra.png
_require ${file_desk_conf} ${file_icon_conf}

########################  MAIN

_echot "------- libfuse2"

sudo apt install -y libfuse2t64

_echot "------- get"

file="CinGG-${ver}-x86_64.AppImage"
url="https://cinelerra-gg.org/download/images/${file}"

[ -f "${pth_opt}" ] || _evalr mkdir ${pth_opt}

if ! [ -f "${pth_opt}/${file}" ]; then
	_ANSWER=${file}
	while ! sudo curl -o "${pth_opt}/${file}" "${url}"; do
		_ask "Unable to donwload:\n$url\nGive a good url to download ${file}\nConfirm"
	done
fi

[ -e "${link_opt}" ] && _evalr rm ${link_opt}
_evalr chmod +x "${pth_opt}/${file}"
_evalr ln -sf "${pth_opt}/${file}" "${link_opt}"

_echot "------- conf"

_evalr cp ${file_icon_conf} "${pth_opt}/"

_evalr cp ${file_desk_conf} "${pth_desk}/"
_evalr chown 1000:1000 "${pth_desk}/${file_desk_conf##*/}"
