#!/bin/bash

#########################  MAIN

_echot "------- install"
packages="docker"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

########################  CONF

_echot "------- add user"
_evalr usermod -aG docker ${USER}

_echot "------- enable"
_service enable docker

_echot "------- start"
_service start docker
