#!/bin/bash
#
# write by Aguy

########################  MAIN

_echot "------- languages"
_echoA "Close language window after validation,"
_askno "Validate to continue"
sudo gnome-language-selector

_echot "------- upgrade"
_eval upgrade

########################  END

_partadd "${_PART}" "${_FILE_DONE}"

########################  RESTART

_echoA "Restart your computer to append configuration"
_askno "Validate to reboot"
sudo reboot
