#!/bin/bash
#
# write by Aguy

########################  MAIN

_echot "------- languages"
_echoA "Select 'Region & language' & 'Manage installed languages' to update required files & close windows,"
_askno "Validate to continue"
sudo gnome-control-center

_echot "------- upgrade"
_eval upgrade

########################  END

_partadd "${_PART}" "${_FILE_DONE}"

########################  RESTART

_echoA "Restart your computer to append configuration"
_askno "Validate to reboot"
sudo reboot
