#!/bin/bash
#
# write by Aguy

_echoT "\n==========================================  ${_PART}"

_echot "------------------ install"
packages="tlp tlp-rdw"
# acpi
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------------------ TLP"
_service enable tlp

########################  END

_echoT "===================== ${_PART} end"
_partadd "${_PART}" "${_FILE_DONE}"
