#!/bin/bash

_echot "------- parts"
packages="libreoffice-calc libreoffice-draw libreoffice-gnome libreoffice-impress libreoffice-math"
_install_pcks ${packages}

_echot "------- tools"
packages=" libreoffice-sdbc-mysql libreoffice-templates libreoffice-wiki-publisher libreoffice-writer"
# libreoffice-sdbc-postgresql
# libreoffice-dmaths libreoffice-librelogo libreoffice-style-breeze libreoffice-style-elementary libreoffice-style-sifr
_install_pcks ${packages}
