#!/bin/bash

########################  DATA

if [ -z ${_QEMU_SHARE+x} ]; then
	anstmp=/hostshare
	_askno "Name of qemu share (${anstmp})"
	_QEMU_SHARE=${_ANSWER:-${anstmp}}
	_confset _QEMU_SHARE "${_QEMU_SHARE}"
fi

if [ -z ${_GUEST_SHARE+x} ]; then
	anstmp=/share
	_askno "Name of guest share (${anstmp})"
	_GUEST_SHARE=${_ANSWER:-${anstmp}}
	_confset _GUEST_SHARE "${_GUEST_SHARE}"
fi

if ! [ -d "${_GUEST_SHARE}" ]; then
	_echot "------- create ${_GUEST_SHARE}"
	_evalr mkdir -p ${_GUEST_SHARE}
fi

########################  9P

_echot "------- mod 9p"
sudo modprobe 9p
[ -d "${_GUEST_SHARE}" ] || sudo mkdir "${_GUEST_SHARE}"
grep -q "^${_QEMU_SHARE}" /proc/mounts || sudo mount "${_GUEST_SHARE}"

_echot "------- autoload 9p"
file=/etc/initramfs-tools/modules
grep -q ^9p ${file} || sudo sh -c "echo '
# qemu share 
9p
9pnet
9pnet_virtio' >> ${file}"
sudo update-initramfs -u

########################  MAIN

_echot "------- fstab"
grep -q "^${_QEMU_SHARE}" /etc/fstab || sudo sh -c "echo '
# qemu share
${_QEMU_SHARE}					${_GUEST_SHARE}		9p	trans=virtio,version=9p2000.L,rw,umask=002						0 0' >> /etc/fstab"

