#!/bin/bash
#
# write by Aguy

_echoT "\n==========================================  ${_PART}"

########################  DATA

if [ -z ${_INC_LAPTOP+x} ]; then
	anstmp=n
	_askno "Apply laptop settings? ($anstmp)"
	_INC_LAPTOP=${_ANSWER:-$anstmp}
	_INC_LAPTOP=${_INC_LAPTOP/n/}
	_confset _INC_LAPTOP "${_INC_LAPTOP}"
fi

if [ -z ${_INC_MUSIC+x} ]; then
	anstmp=n
	_askno "Install 'Music' softwares? ($anstmp)"
	_INC_MUSIC=${_ANSWER:-$anstmp}
	_INC_MUSIC=${_INC_MUSIC/n/}
	_confset _INC_MUSIC "${_INC_MUSIC}"
fi

if [ -z ${_INC_GRAPHIC+x} ]; then
	anstmp=n
	_askno "Install 'Graphic' softwares? ($anstmp)"
	_INC_GRAPHIC=${_ANSWER:-$anstmp}
	_INC_GRAPHIC=${_INC_GRAPHIC/n/}
	_confset _INC_GRAPHIC "${_INC_GRAPHIC}"
fi

if [ -z ${_INC_VIDEO+x} ]; then
	anstmp=n
	_askno "Install 'videos' softwares? ($anstmp)"
	_INC_VIDEO=${_ANSWER:-$anstmp}
	_INC_VIDEO=${_INC_VIDEO/n/}
	_confset _INC_VIDEO "${_INC_VIDEO}"
fi

[ -z ${_INC_FREECAD+x} ]; then
	anstmp=n
	_askno "Install 'Freecad'? ($anstmp)"
	_INC_FREECAD=${_ANSWER:-$anstmp}
	_INC_FREECAD=${_INC_FREECAD/n/}
	_confset _INC_FREECAD "${_INC_FREECAD}"
fi

if [ -z ${_INC_VMWARE+x} ]; then
	anstmp=n
	_askno "Install 'Vmware'? ($anstmp)"
	_INC_VMWARE=${_ANSWER:-$anstmp}
	_INC_VMWARE=${_INC_VMWARE/n/}
	_confset _INC_VMWARE "${_INC_VMWARE}"
fi

if [ -z ${_INC_VIRTUALBOX+x} ]; then
	anstmp=n
	_askno "Install 'Virtualbox'? ($anstmp)"
	_INC_VIRTUALBOX=${_ANSWER:-$anstmp}
	_INC_VIRTUALBOX=${_INC_VIRTUALBOX/n/}
	_confset _INC_VIRTUALBOX "${_INC_VIRTUALBOX}"
fi

if [ -z ${_INC_DEV+x} ]; then
	anstmp=n
	_askno "Install 'developer' softwares? ($anstmp)"
	_INC_DEV=${_ANSWER:-$anstmp}
	_INC_DEV=${_INC_DEV/n/}
	_confset _INC_DEV "${_INC_DEV}"
fi

if [ -z ${_INC_NETWORK+x} ]; then
	anstmp=n
	_askno "Install 'network' softwares? ($anstmp)"
	_INC_NETWORK=${_ANSWER:-$anstmp}
	_INC_NETWORK=${_INC_NETWORK/n/}
	_confset _INC_NETWORK "${_INC_NETWORK}"
fi
	
########################  END

_echoT "===================== ${_PART} end"
_partadd "${_PART}" "${_FILE_DONE}"
