#!/bin/bash
#
# write by Aguy

########################  MAIN

_echot "------- client conf"

file=/etc/ssh/ssh_config
sudo [ -f "${file}" ] && sudo cp -a "${file}" "${file}.keep$(date +%s)"
sudo sed -i "s/^#\(\s*GSSAPIAuthentication\).*/ \1 no/" $file
sudo sed -i "/Host\s\+\*/ s|#\s\+||" ${file}
! sudo grep -q ServerAliveInterval ${file} && sudo sh -c "echo '    ServerAliveInterval 240' >> ${file}"

_echot "------- server conf"

file=/etc/ssh/sshd_config
if [ -f "${file}" ]; then
	sudo [ -f "${file}" ] && sudo cp -a "${file}" "${file}.keep$(date +%s)"
	! grep -q "UseDNS" ${file} && echo "UseDNS no" | sudo tee -a $file
	sudo systemctl restart sshd.service
fi

