#!/bin/bash

pth_origin=/home/shared/.themes/.origin

#############  ORCHIS

id=Orchis-theme
_echot "------- install ${id}"
pth=${pth_origin}/${id}
if [ -d ${pth} ]; then
	_eval git -C ${pth} pull
else
	_eval git clone https://github.com/vinceliuice/${id} ${pth}
fi
_eval ${pth}/install.sh -d ~/.themes -c dark -s compact -l
_eval ${pth}/install.sh -d ~/.themes -c dark -s compact -l --shell --round 8px
_eval ${pth}/install.sh -d ~/.themes -c dark -s compact -l --shell --round 8px -t teal
_eval ${pth}/install.sh -d ~/.themes -c dark -s compact -l --shell --round 8px -t orange

theme=Orchis-Orange-Dark-Compact

#############  GRAPHITE

id=Graphite-gtk-theme
_echot "------- install ${id}"
pth=${pth_origin}/${id}
if [ -d ${pth} ]; then
	_eval git -C ${pth} pull
else
	_eval git clone https://github.com/vinceliuice/${id} ${pth}
fi
_eval ${pth}/install.sh -d ~/.themes -c dark -s compact -l
_eval ${pth}/install.sh -d ~/.themes -c dark -s compact -l --round 8px
_eval ${pth}/install.sh -d ~/.themes -c dark -s compact -l --round 8px -t teal
_eval ${pth}/install.sh -d ~/.themes -c dark -s compact -l --round 8px -t orange

theme=WhiteSur-Dark

#############  WHITE-SUR

id=WhiteSur-gtk-theme
_echot "------- install ${id}"
pth=${pth_origin}/${id}
if [ -d ${pth} ]; then
	_eval git -C ${pth} pull
else
	_eval git clone https://github.com/vinceliuice/${id} ${pth}
fi
_eval ${pth}/install.sh -d ~/.themes -c dark -s nord -l
_eval ${pth}/install.sh -d ~/.themes -c dark -s nord -l --round
_eval ${pth}/install.sh -d ~/.themes -c dark -s nord -l --round -t pink
_eval ${pth}/install.sh -d ~/.themes -c dark -s nord -l --round -t orange

theme=WhiteSur-Dark-orange-nord

###########  FLUENT

id=Fluent-gtk-theme
_echot "------- install ${id}"
pth=${pth_origin}/${id}
if [ -d ${pth} ]; then
	_eval git -C ${pth} pull
else
	_eval git clone https://github.com/vinceliuice/${id} ${pth}
fi
cd ${pth}
_eval ${pth}/install.sh -d ~/.themes -c dark -s compact -l
_eval ${pth}/install.sh -d ~/.themes -c dark -s compact -t teal -l
_eval ${pth}/install.sh -d ~/.themes -c dark -t orange -l
_eval ${pth}install.sh -d ~/.themes -c dark -s compact -t orange -l
_eval ${pth}/install.sh -d ~/.themes -c dark -s compact -t orange --tweaks round -l

theme=Fluent-orange-Dark-compact

########################  DATA

_askyn "Apply themes '${theme}'' to desktop"
if [ "${_ANSWER}" = y ]; then
	gsettings set org.gnome.desktop.interface gtk-theme "${theme}"
	gsettings set org.gnome.desktop.wm.preferences theme "${theme}"
	gsettings set org.gnome.desktop.interface icon-theme "${theme}"
fi

_echoA "You can change the theme from 'gnome-tweaks'"
_askno "Validate to continue"
