#!/bin/bash
#
# write by Aguy

########################  MAIN

_echoT "\n==========================================  ${_PART}"

_echot "------------------ update"
sudo apt update

_echot "------------------ dist-upgrade"
sudo apt -y dist-upgrade

_echot "------------------ clean"
sudo apt autoremove -y
sudo apt clean
sudo apt autoclean

########################  END

_echoT "===================== ${_PART} end"
_partadd "${_PART}" "${_FILE_DONE}"

