#!/bin/bash
#
# write by Aguy

########################  MAIN

_echot "------- update"
${_CMD} update

_echot "------- dist-upgrade"
${_CMD} -y dist-upgrade

_echot "------- clean"
${_CMD} -y autoremove
${_CMD} clean
${_CMD} autoclean

########################  END

_partadd "${_PART}" "${_FILE_DONE}"
